version: '3'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    restart: always
    stdin_open: true
    tty: true
  csv_receiver:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: 'development'
    env_file:
      - .env
    volumes:
      - ./node_modules:/node_modules
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./src:/usr/src/app/src
    depends_on:
      - sqlite3
  migration:
    build: .
    image: csv_receiver
    command: ['npx', 'prisma', 'migrate', 'dev', '--name', 'initialize']
    links:
      - sqlite3
    depends_on:
      - sqlite3

volumes:
  database:
    driver: local
